events {
  worker_connections 1024;
}

http {
  upstream webhook_backend {
    server webhook-service-1:9999;
    server webhook-service-2:9999;
  }

  upstream storage_backend {
    server storage-service-1:9998;
    server storage-service-2:9998;
  }

  upstream streaming_backend {
    server streaming-service-1:9997;
    server streaming-service-2:9997;
  }

  server {
    listen 9999;
    location / {
      proxy_pass http://webhook_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 9998;
    location / {
      proxy_pass http://storage_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 9997;
    location / {
      proxy_pass http://streaming_backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
